// Mocks generated by Mockito 5.4.6 from annotations
// in bagistruk/test/presentation/ocr/screens/share_auto_scan_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i14;

import 'package:bagistruk/core/error/result.dart' as _i5;
import 'package:bagistruk/domain/entities/auth_snapshot.dart' as _i4;
import 'package:bagistruk/domain/entities/monthly_spending_insight.dart'
    as _i10;
import 'package:bagistruk/domain/entities/ocr_credit_status.dart' as _i9;
import 'package:bagistruk/domain/entities/ocr_result.dart' as _i13;
import 'package:bagistruk/domain/entities/transfer_bank_info.dart' as _i11;
import 'package:bagistruk/domain/entities/user_profile.dart' as _i8;
import 'package:bagistruk/domain/repositories/i_auth_repository.dart' as _i2;
import 'package:bagistruk/domain/repositories/i_ocr_repository.dart' as _i12;
import 'package:bagistruk/domain/repositories/i_profile_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i2.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  bool get isEmailConfirmed =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailConfirmed),
            returnValue: false,
          )
          as bool);

  @override
  bool get isPasswordRecovery =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordRecovery),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Stream<String?> watchUserId() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserId, []),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);

  @override
  _i3.Stream<_i4.AuthSnapshot> watchAuthState() =>
      (super.noSuchMethod(
            Invocation.method(#watchAuthState, []),
            returnValue: _i3.Stream<_i4.AuthSnapshot>.empty(),
          )
          as _i3.Stream<_i4.AuthSnapshot>);

  @override
  _i3.Future<_i5.Result<String>> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i3.Future<_i5.Result<String>>.value(
              _i6.dummyValue<_i5.Result<String>>(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<String>>);

  @override
  _i3.Future<_i5.Result<String>> ensureSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#ensureSignedIn, []),
            returnValue: _i3.Future<_i5.Result<String>>.value(
              _i6.dummyValue<_i5.Result<String>>(
                this,
                Invocation.method(#ensureSignedIn, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<String>>);

  @override
  _i3.Future<_i5.Result<void>> linkEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#linkEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> signInWithPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> sendEmailOtp({
    required String? email,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailOtp, [], {
              #email: email,
              #languageCode: languageCode,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#sendEmailOtp, [], {
                  #email: email,
                  #languageCode: languageCode,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> verifyEmailOtp({
    required String? email,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailOtp, [], {
              #email: email,
              #token: token,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#verifyEmailOtp, [], {
                  #email: email,
                  #token: token,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> resendEmailChange({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailChange, [], {#email: email}),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#resendEmailChange, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> recoverSessionFromUri(Uri? uri) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSessionFromUri, [uri]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#recoverSessionFromUri, [uri]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> resetPasswordForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordForEmail, [email]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#resetPasswordForEmail, [email]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updatePassword, [newPassword]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<void> clearPasswordRecovery() =>
      (super.noSuchMethod(
            Invocation.method(#clearPasswordRecovery, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i7.IProfileRepository {
  MockIProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Result<_i8.UserProfile>> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i3.Future<_i5.Result<_i8.UserProfile>>.value(
              _i6.dummyValue<_i5.Result<_i8.UserProfile>>(
                this,
                Invocation.method(#getCurrentProfile, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i8.UserProfile>>);

  @override
  _i3.Future<_i5.Result<void>> updateDisplayName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [name]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateDisplayName, [name]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateDefaultCurrency(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#updateDefaultCurrency, [code]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateDefaultCurrency, [code]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateLanguage(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#updateLanguage, [code]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateLanguage, [code]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateOnboardingPreferences({
    required String? currencyCode,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnboardingPreferences, [], {
              #currencyCode: currencyCode,
              #languageCode: languageCode,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateOnboardingPreferences, [], {
                  #currencyCode: currencyCode,
                  #languageCode: languageCode,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateThemePref(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#updateThemePref, [mode]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateThemePref, [mode]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> setMarketingEmailOptIn({
    required bool? optedIn,
    required String? source,
    String? preferredLanguage = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setMarketingEmailOptIn, [], {
              #optedIn: optedIn,
              #source: source,
              #preferredLanguage: preferredLanguage,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#setMarketingEmailOptIn, [], {
                  #optedIn: optedIn,
                  #source: source,
                  #preferredLanguage: preferredLanguage,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> recordLegalAcceptance({
    required int? termsVersion,
    required int? privacyVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordLegalAcceptance, [], {
              #termsVersion: termsVersion,
              #privacyVersion: privacyVersion,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#recordLegalAcceptance, [], {
                  #termsVersion: termsVersion,
                  #privacyVersion: privacyVersion,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> markWelcomed() =>
      (super.noSuchMethod(
            Invocation.method(#markWelcomed, []),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#markWelcomed, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> markOnboardingCompleted({
    required int? version,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markOnboardingCompleted, [], {
              #version: version,
            }),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#markOnboardingCompleted, [], {
                  #version: version,
                }),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> setIsAdult({required bool? isAdult}) =>
      (super.noSuchMethod(
            Invocation.method(#setIsAdult, [], {#isAdult: isAdult}),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#setIsAdult, [], {#isAdult: isAdult}),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<_i9.OcrCreditStatus>> getOcrCreditStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getOcrCreditStatus, []),
            returnValue: _i3.Future<_i5.Result<_i9.OcrCreditStatus>>.value(
              _i6.dummyValue<_i5.Result<_i9.OcrCreditStatus>>(
                this,
                Invocation.method(#getOcrCreditStatus, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i9.OcrCreditStatus>>);

  @override
  _i3.Future<_i5.Result<_i10.MonthlySpendingInsight>>
  getMonthlySpendingInsight({
    required DateTime? month,
    required String? currencyCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlySpendingInsight, [], {
              #month: month,
              #currencyCode: currencyCode,
            }),
            returnValue:
                _i3.Future<_i5.Result<_i10.MonthlySpendingInsight>>.value(
                  _i6.dummyValue<_i5.Result<_i10.MonthlySpendingInsight>>(
                    this,
                    Invocation.method(#getMonthlySpendingInsight, [], {
                      #month: month,
                      #currencyCode: currencyCode,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<_i10.MonthlySpendingInsight>>);

  @override
  _i3.Future<_i5.Result<_i11.TransferBankInfo?>> getTransferBankInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getTransferBankInfo, []),
            returnValue: _i3.Future<_i5.Result<_i11.TransferBankInfo?>>.value(
              _i6.dummyValue<_i5.Result<_i11.TransferBankInfo?>>(
                this,
                Invocation.method(#getTransferBankInfo, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i11.TransferBankInfo?>>);

  @override
  _i3.Future<_i5.Result<void>> updateTransferBankInfo(
    _i11.TransferBankInfo? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransferBankInfo, [info]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateTransferBankInfo, [info]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> touchLastActive() =>
      (super.noSuchMethod(
            Invocation.method(#touchLastActive, []),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#touchLastActive, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);
}

/// A class which mocks [IOCRRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOCRRepository extends _i1.Mock implements _i12.IOCRRepository {
  MockIOCRRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Result<_i13.OcrResult>> processReceipt(
    List<_i14.Uint8List>? imagesBytes, {
    String? hint,
    String? currency,
    Map<String, String>? fingerprintHeaders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processReceipt,
              [imagesBytes],
              {
                #hint: hint,
                #currency: currency,
                #fingerprintHeaders: fingerprintHeaders,
              },
            ),
            returnValue: _i3.Future<_i5.Result<_i13.OcrResult>>.value(
              _i6.dummyValue<_i5.Result<_i13.OcrResult>>(
                this,
                Invocation.method(
                  #processReceipt,
                  [imagesBytes],
                  {
                    #hint: hint,
                    #currency: currency,
                    #fingerprintHeaders: fingerprintHeaders,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i13.OcrResult>>);
}
